name: presence
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependency_overrides:
  url_launcher_web: 2.0.6

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  open_file: ^3.1.0
  cupertino_icons: ^1.0.2
  # firebase
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0
  syncfusion_flutter_gauges: ^19.4.56
  syncfusion_flutter_pdf: ^19.1.56-beta
  fluttertoast: ^8.0.9
  # firebase_database_web: ^0.2.0+7
  flutter_animation_progress_bar: ^2.0.1
  font_awesome_flutter: ^10.1.0
  universal_html: ^2.0.8
  overlay_support: ^1.2.1
  internet_connection_checker: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.1.2 
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  
  flutter_lints: ^1.0.0




flutter_native_splash:
  color: "#ffffff"
  image: "image/Presence_loading.png"
  android: true
  ios: true




flutter_icons:
    android: true
    ios: true
    image_path: "image/Presence_logo.png"  


flutter:
  uses-material-design: true
  assets:
  - image/Presence_loading.png
  - image/Presence_logo.png
  - image/Presence_name.png
  - image/faculty_profile.png
  - image/student_profile.png
  - image/institute_profile.png
  - image/contact.png
  - image/privacy.png
  - image/contactsu.png
  - image/img.png
  - image/feedback.png
  - image/OIP.jfif
  - image/stupro.png
  - image/teapro.png
  - image/inspro.jfif
  - image/fac.jfif
  - image/insta.jfif
  - image/ws.jfif
  - assets/images/
  - assets/images/name.png
  - assets/images/student.png
  - assets/images/teacher.png
  - assets/images/insLogo.png
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700